name: Create Pull Request

on:
  pull_request:
    branches: [main]

permissions:
  security-events: write
  contents: read
  pages: write
  id-token: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled

      - name: Check for open source vulnerabilities
        id: snyk_open_source
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --all-projects --sarif-file-output=snyk-open-source.sarif

#      - name: Check for code vulnerabilities
#        id: snyk_code
#        uses: snyk/actions/node@master
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#        with:
#          command: code test
#          args: --all-projects --sarif-file-output=snyk-code.sarif
#
#      - name: Check Dockerfile for vulnerabilities
#        id: snyk_docker
#        uses: snyk/actions/docker@master
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#        with:
#          dockerfile: Dockerfile
#          args: --sarif-file-output=snyk-docker.sarif

      - name: Upload open source vulnerabilities to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: snyk-open-source.sarif
          category: "Snyk Open Source"

#      - name: Upload code vulnerabilities to GitHub Code Scanning
#        uses: github/codeql-action/upload-sarif@v2
#        if: always()
#        with:
#          sarif_file: snyk-code.sarif
#          category: "Snyk Code"

#      - name: Upload Dockerfile vulnerabilities to GitHub Code Scanning
#        uses: github/codeql-action/upload-sarif@v2
#        if: always()
#        with:
#          sarif_file: snyk-docker.sarif
#          category: "Snyk Dockerfile"

      - name: Check Snyk scan results
        if: failure()
        run: |
          echo "Vulnerabilities or errors found in Snyk scans. Please review the Snyk reports and fix the issues."
          exit 1
