name: Create Pull Request

on:
  pull_request:
    branches: [ main ]

permissions:
  security-events: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled

      - name: Snyk Scan
        uses: ./.github/actions/snyk-scan
